site_name: Publish Site
site_url: https://publish-site.rvid.eu/
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Configuration:
      - Backend: config/backend.md
      - GitHub Action: config/action.md
  - Other:
    - to-do.md
    - credits.md
    - demo.md